<a href="https://colab.research.google.com/github/kjedrzejczak/Wprowadzenie_do_sieci_neuronowych-Tensorflow_2.0-Keras/blob/main/02_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Skalar

In [ ]:
scalar = 3
print(scalar)
print(type(scalar))

3
<class 'int'>


In [ ]:
scalar = 3.
print(scalar)
print(type(scalar))

3.0
<class 'float'>


Wektor

In [ ]:
import numpy as np

vector = np.array([2, 4, -6, 5])
print(vector)
print(type(vector))
print(vector.shape)
print(vector.dtype)
print(vector.ndim)
print(len(vector))

[ 2  4 -6  5]
<class 'numpy.ndarray'>
(4,)
int64
1
4


In [ ]:
vector = np.array([[2, 4, -6, 5], dtype='float')
print(vector)
print(type(vector))
print(vector.shape)
print(vector.dtype)
print(vector.ndim)
print(len(vector))

[ 2.  4. -6.  5.]
<class 'numpy.ndarray'>
(4,)
float64
1


In [ ]:
vector = np.array([[2, 4, -6, 5], [1, 2, 3, 4]], dtype='float')
print(vector)
print(type(vector))
print(vector.shape)
print(vector.dtype)
print(vector.ndim)
print(len(vector))

[[ 2.  4. -6.  5.]
 [ 1.  2.  3.  4.]]
<class 'numpy.ndarray'>
(2, 4)
float64
2
2


Tensor

In [ ]:
tensor = np.array([[[2, 4, -6, 5],
                    [1, 2, 3, 4]],
                  [[2, 4, -6, 5],
                   [1, 2, 3, 4]]], dtype='float')
print(tensor)
print(type(tensor))
print(tensor.shape)
print(tensor.dtype)
print(tensor.ndim)
print(len(tensor))

[[[ 2.  4. -6.  5.]
  [ 1.  2.  3.  4.]]

 [[ 2.  4. -6.  5.]
  [ 1.  2.  3.  4.]]]
<class 'numpy.ndarray'>
(2, 2, 4)
float64
3
2


In [ ]:
tensor = np.array([[[2, 4, -6, 5],
                    [1, 2, 3, 4]],
                   [[2, 4, -6, 5],
                   [1, 2, 3, 4]],
                   [[2, 4, -6, 5],
                    [1, 2, 3, 4]]], dtype='float')
print(tensor)
print(type(tensor))
print(tensor.shape)
print(tensor.dtype)
print(tensor.ndim)
print(len(tensor))

[[[ 2.  4. -6.  5.]
  [ 1.  2.  3.  4.]]

 [[ 2.  4. -6.  5.]
  [ 1.  2.  3.  4.]]

 [[ 2.  4. -6.  5.]
  [ 1.  2.  3.  4.]]]
<class 'numpy.ndarray'>
(3, 2, 4)
float64
3
3


In [ ]:
tensor[0]

array([[ 2.,  4., -6.,  5.],
       [ 1.,  2.,  3.,  4.]])