<a href="https://colab.research.google.com/github/kjedrzejczak/Wprowadzenie_do_sieci_neuronowych-Tensorflow_2.0-Keras/blob/main/09_Metryki_regresji.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

In [ ]:
y_true = 100 + 20 * np.random.randn(50)
y_true

array([119.71362321, 100.00549596, 106.8141078 ,  80.3063041 ,
        80.31350169, 101.01476071, 101.54136144,  88.82222297,
       101.4036758 ,  73.12933471,  95.80238199,  87.29191962,
        71.77787534,  85.97213028, 116.14948812,  97.8364535 ,
       101.06774794, 110.06289787,  73.31659599, 117.4863958 ,
        89.9533419 ,  79.91974863, 131.54545098,  77.09104155,
       126.79285556,  97.51687826,  93.62770158,  85.16446844,
        89.15341859,  71.9705611 ,  81.12572585, 101.39593319,
       111.17022235, 121.93757821, 101.23283718,  95.7081548 ,
       101.4443692 , 130.19343421,  73.11533547, 122.93108627,
       131.30671868, 105.54236231,  55.01551033, 133.91324541,
       124.00666547, 107.6059134 ,  77.24126979, 127.01457925,
       104.56198073,  95.29339168])

In [ ]:
y_pred = y_true + 10 * np.random.randn(50)
y_pred

array([117.77127633,  96.5127642 ,  95.98067859,  81.02260836,
        89.74630419,  89.8282087 , 106.42572766,  99.52200424,
        94.1104238 ,  78.0779985 ,  99.71898959,  89.20962587,
        53.51606042,  81.29774729, 103.66863756, 100.78864839,
       102.36450752, 109.26914955,  67.61060037, 113.86094372,
        76.65995487,  84.32059854, 128.00056184,  83.08353697,
       138.58417383,  99.79470123, 102.60060165,  69.89853739,
        77.74869127,  68.8918978 ,  78.28790607, 107.27703004,
       106.68767136, 108.4898205 ,  95.79091778,  90.29225283,
       114.55023408, 130.55649662,  76.04455864, 135.90117467,
       130.2900955 , 116.14061924,  43.67869092, 118.27656684,
       107.9173354 ,  97.19080845,  82.02231323, 126.99830728,
        92.24962974,  98.31540128])

In [ ]:
results = pd.DataFrame({'y_true':y_true, 'y_pred':y_pred})
results['error'] = results['y_true'] - results['y_pred']
results.head()

y_true      y_pred      error
0  119.713623  117.771276   1.942347
1  100.005496   96.512764   3.492732
2  106.814108   95.980679  10.833429
3   80.306304   81.022608  -0.716304
4   80.313502   89.746304  -9.432803

Metryki

In [ ]:
def plot_regression_results(y_true, y_pred):
  results = pd.DataFrame({'y_true':y_true, 'y_pred':y_pred})
  min = results[['y_true', 'y_pred']].min().min()
  max = results[['y_true', 'y_pred']].max().max()

  fig = go.Figure(data=[go.Scatter(x=results['y_true'], y=results['y_pred'], mode='markers'),
                         go.Scatter(x=[min, max], y=[min, max])],
                   layout=go.Layout(showlegend=False, width=800,
                                    xaxis_title='y_true',
                                    yaxis_title='y_pred',
                                    title='Regression results'))
  fig.show()

plot_regression_results(y_true, y_pred)

Rozkład błędu

In [ ]:
y_true = 100 + 20 * np.random.randn(1000)
y_pred = y_true + 10 * np.random.randn(1000)
results = pd.DataFrame({'y_true':y_true, 'y_pred':y_pred})
results['error'] = results['y_true'] - results['y_pred']

px.histogram(results, x='error', nbins=50, width=800)

Mean Absolut Error MAE

In [ ]:
def mean_absolute_error(y_true, y_pred):
  return abs(y_true - y_pred).sum() / len(y_true)


mean_absolute_error(y_true, y_pred)

8.139852777003442

In [ ]:
from tensorflow.keras.losses import mean_absolute_error

mean_absolute_error(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float64, numpy=8.139852777003442>

In [ ]:
from sklearn.metrics import mean_absolute_error

mean_absolute_error(y_true, y_pred)

8.139852777003442

Mean Squared Error

In [ ]:
def mean_squared_error(y_true, y_pred):
  return ((y_true - y_pred) ** 2).sum() / len(y_true)

mean_squared_error(y_true, y_pred)

104.61336867050908

In [ ]:
from tensorflow.keras.losses import mean_squared_error

mean_squared_error(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float64, numpy=104.61336867050908>

In [ ]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y_true, y_pred)

104.61336867050908

Root Mean Squared Error  - wartość +/-

In [ ]:
def root_mean_squared_error(y_true, y_pred):
  return np.sqrt(((y_true - y_pred) **2)).sum() / len(y_true)

root_mean_squared_error(y_true, y_pred)

8.139852777003442

In [ ]:
np.sqrt(mean_squared_error(y_true, y_pred))

10.228067689965151

Max error

In [ ]:
def max_error(y_true, y_pred):
  return abs(y_true - y_pred).max()

max_error(y_true, y_pred)

32.24620642661853

R2_score   - najlepiej jak wartość jak najbliżej wartości 1

In [ ]:
def r2_score(y_true, y_pred):
  numerator = ((y_true - y_pred) ** 2).sum()
  denominator = ((y_true - y_true.mean()) ** 2).sum()
  try:
    r2 = 1 - numerator / denominator
  except ZeroDivisionError:
    print('Dzielenie przez 0')
  return r2


r2_score(y_true, y_pred)

0.734345736716179