<a href="https://colab.research.google.com/github/kjedrzejczak/Wprowadzenie_do_sieci_neuronowych-Tensorflow_2.0-Keras/blob/main/13_Keras_wprowadzenie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px
tf.__version__

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.activations import linear, sigmoid, relu, tanh

# Przykład klasyfikacji binarnej

In [ ]:
data = np.random.randn(1000, 150)
labels = np.random.randint(2, size=(1000, 1))

print(data.shape)
print(labels.shape)

(1000, 150)
(1000, 1)


In [ ]:
print(data[0])

[ 1.9636225  -2.19347182 -0.39446512 -0.9505714  -0.98524416 -0.5859358
 -1.72587605  0.08481841  0.07266367 -0.54544138  0.85153737 -1.13868836
 -0.23919026  1.81593287  0.36245511  0.07143538  0.94759371  0.69837341
  1.90956404  1.34014724 -1.22622708  2.12605648  0.19721451 -1.53770403
 -0.58327021  1.69841043 -0.06313284  0.17200019 -1.09239766  1.02710454
  0.04455847 -1.56803586 -0.67104489 -1.58502252  2.30134683  0.07210816
  0.91001202  0.55612318  0.03215989 -1.40743207  0.52235048 -0.74389425
  2.59726815  0.14852598 -0.2072088  -0.80209226 -1.20998694 -0.08384379
  1.129429    1.14718179 -0.11268252  0.43596946 -0.61809135  0.00485441
  0.95103874  0.28993866  0.54413968  2.30388882 -0.54798488  1.29459183
 -0.12365762  2.25414879 -1.18526242 -0.20583753 -0.42708878 -0.66792491
 -0.54472904  0.28801985 -0.42752228 -0.26416763  0.08153265  0.28318597
  0.72219774 -0.50460499 -1.23746043 -2.97085326 -0.36750582 -0.11667138
  0.86336576  0.04163821  0.21013388  0.87029435 -2.

In [ ]:
print(labels[0])

[0]


In [ ]:
np.unique(labels)

array([0, 1])

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150, )))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20)

Epoch 1/20
32/32 [==============================] - 1s 2ms/step - loss: 0.7841 - accuracy: 0.5280
Epoch 2/20
32/32 [==============================] - 0s 2ms/step - loss: 0.6937 - accuracy: 0.5770
Epoch 3/20
32/32 [==============================] - 0s 2ms/step - loss: 0.6482 - accuracy: 0.6040
Epoch 4/20
32/32 [==============================] - 0s 2ms/step - loss: 0.6123 - accuracy: 0.6500
Epoch 5/20
32/32 [==============================] - 0s 2ms/step - loss: 0.5816 - accuracy: 0.7010
Epoch 6/20
32/32 [==============================] - 0s 2ms/step - loss: 0.5558 - accuracy: 0.7220
Epoch 7/20
32/32 [==============================] - 0s 2ms/step - loss: 0.5302 - accuracy: 0.7490
Epoch 8/20
32/32 [==============================] - 0s 2ms/step - loss: 0.5075 - accuracy: 0.7660
Epoch 9/20
32/32 [==============================] - 0s 2ms/step - loss: 0.4857 - accuracy: 0.7890
Epoch 10/20
32/32 [==============================] - 0s 3ms/step - loss: 0.4640 - accuracy: 0.8150
Epoch 11/20
32/32 [

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150, )))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=30)  # batch size == ilość próbek

Epoch 1/20
34/34 [==============================] - 1s 2ms/step - loss: 0.8185 - accuracy: 0.4950
Epoch 2/20
34/34 [==============================] - 0s 2ms/step - loss: 0.7227 - accuracy: 0.5610
Epoch 3/20
34/34 [==============================] - 0s 3ms/step - loss: 0.6695 - accuracy: 0.5960
Epoch 4/20
34/34 [==============================] - 0s 3ms/step - loss: 0.6263 - accuracy: 0.6470
Epoch 5/20
34/34 [==============================] - 0s 3ms/step - loss: 0.5924 - accuracy: 0.6870
Epoch 6/20
34/34 [==============================] - 0s 3ms/step - loss: 0.5613 - accuracy: 0.7340
Epoch 7/20
34/34 [==============================] - 0s 3ms/step - loss: 0.5330 - accuracy: 0.7570
Epoch 8/20
34/34 [==============================] - 0s 3ms/step - loss: 0.5065 - accuracy: 0.7840
Epoch 9/20
34/34 [==============================] - 0s 2ms/step - loss: 0.4817 - accuracy: 0.8170
Epoch 10/20
34/34 [==============================] - 0s 2ms/step - loss: 0.4583 - accuracy: 0.8250
Epoch 11/20
34/34 [

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150, )))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=30, validation_split=0.2)  # 20% danych do procesu walidacji ----- val_accuracy jest ważny !!

Epoch 1/20
27/27 [==============================] - 1s 12ms/step - loss: 1.1230 - accuracy: 0.5125 - val_loss: 1.0875 - val_accuracy: 0.4650
Epoch 2/20
27/27 [==============================] - 0s 3ms/step - loss: 0.8694 - accuracy: 0.5288 - val_loss: 0.9586 - val_accuracy: 0.4300
Epoch 3/20
27/27 [==============================] - 0s 3ms/step - loss: 0.7327 - accuracy: 0.5663 - val_loss: 0.8826 - val_accuracy: 0.4550
Epoch 4/20
27/27 [==============================] - 0s 4ms/step - loss: 0.6553 - accuracy: 0.6275 - val_loss: 0.8497 - val_accuracy: 0.4550
Epoch 5/20
27/27 [==============================] - 0s 5ms/step - loss: 0.6074 - accuracy: 0.6737 - val_loss: 0.8329 - val_accuracy: 0.4800
Epoch 6/20
27/27 [==============================] - 0s 4ms/step - loss: 0.5703 - accuracy: 0.7175 - val_loss: 0.8252 - val_accuracy: 0.4800
Epoch 7/20
27/27 [==============================] - 0s 4ms/step - loss: 0.5376 - accuracy: 0.7513 - val_loss: 0.8231 - val_accuracy: 0.4900
Epoch 8/20
27/27 [=

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150, )))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=30, validation_split=0.2, verbose=0)  # 0 - tylko końcowy wynik bez kolejnych kroków

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150, )))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=30, validation_split=0.2, verbose=0)


metrics = history.history
metrics.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [ ]:
metrics['accuracy']

[0.4937500059604645,
 0.5475000143051147,
 0.5849999785423279,
 0.6237499713897705,
 0.6675000190734863,
 0.6912500262260437,
 0.7337499856948853,
 0.7587500214576721,
 0.7787500023841858,
 0.8125,
 0.8274999856948853,
 0.8475000262260437,
 0.8600000143051147,
 0.8774999976158142,
 0.8962500095367432,
 0.9037500023841858,
 0.9162499904632568,
 0.9262499809265137,
 0.9487500190734863,
 0.9587500095367432]

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150, )))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=30, validation_split=0.2, verbose=1)

Epoch 1/20
27/27 [==============================] - 1s 9ms/step - loss: 0.8209 - accuracy: 0.4750 - val_loss: 0.8720 - val_accuracy: 0.4600
Epoch 2/20
27/27 [==============================] - 0s 4ms/step - loss: 0.7305 - accuracy: 0.5337 - val_loss: 0.8493 - val_accuracy: 0.4550
Epoch 3/20
27/27 [==============================] - 0s 4ms/step - loss: 0.6789 - accuracy: 0.5825 - val_loss: 0.8315 - val_accuracy: 0.4650
Epoch 4/20
27/27 [==============================] - 0s 3ms/step - loss: 0.6363 - accuracy: 0.6338 - val_loss: 0.8202 - val_accuracy: 0.4800
Epoch 5/20
27/27 [==============================] - 0s 3ms/step - loss: 0.6016 - accuracy: 0.6725 - val_loss: 0.8155 - val_accuracy: 0.4850
Epoch 6/20
27/27 [==============================] - 0s 3ms/step - loss: 0.5704 - accuracy: 0.7088 - val_loss: 0.8150 - val_accuracy: 0.4850
Epoch 7/20
27/27 [==============================] - 0s 4ms/step - loss: 0.5411 - accuracy: 0.7437 - val_loss: 0.8135 - val_accuracy: 0.4850
Epoch 8/20
27/27 [==

In [ ]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5, 1))

In [ ]:
model.predict(test_data)  # zwraca prawdopodobieństwo do przynalezności do danej grupy

1/1 [==============================] - 0s 120ms/step


array([[0.44635308],
       [0.31332767],
       [0.59464186],
       [0.7315648 ],
       [0.7678118 ]], dtype=float32)

In [ ]:
# model.predict_proba(test_data)  nie działa 😶‍🌫️

In [ ]:
# model.predict_classes(test_data) nie działa 😶‍🌫️

In [ ]:
predictions = (model.predict(test_data) > 0.5).astype("int32") # 👈👈👈👈👈👈👈👈👈👈👈👈👈 !!!!!!!!!!!!!!!!!!1
predictions

1/1 [==============================] - 0s 34ms/step


array([[0],
       [0],
       [1],
       [1],
       [1]], dtype=int32)

# Przykład klasyfikacji wieloklasowej

In [ ]:
data = np.random.random((1000, 150))
labels = np.random.randint(10, size=(1000, 1))

In [ ]:
np.unique(labels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(data.shape)
print(labels.shape)

(1000, 150)
(1000, 1)


In [ ]:
from tensorflow.keras.utils import to_categorical  # kodowanie 0 1

labels = to_categorical(labels, num_classes=10)
labels[1]

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150, )))
model.add(Dense(units=10, activation='softmax'))  # 10 kategorji więc 10 neuronów na wyjściu

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',     # categorical 😶‍🌫️👈
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/30
25/25 [==============================] - 1s 15ms/step - loss: 2.3840 - accuracy: 0.0900 - val_loss: 2.3550 - val_accuracy: 0.0900
Epoch 2/30
25/25 [==============================] - 0s 5ms/step - loss: 2.3124 - accuracy: 0.1175 - val_loss: 2.3476 - val_accuracy: 0.1150
Epoch 3/30
25/25 [==============================] - 0s 5ms/step - loss: 2.2937 - accuracy: 0.1262 - val_loss: 2.3371 - val_accuracy: 0.1250
Epoch 4/30
25/25 [==============================] - 0s 5ms/step - loss: 2.2772 - accuracy: 0.1375 - val_loss: 2.3457 - val_accuracy: 0.1100
Epoch 5/30
25/25 [==============================] - 0s 5ms/step - loss: 2.2684 - accuracy: 0.1587 - val_loss: 2.3438 - val_accuracy: 0.1050
Epoch 6/30
25/25 [==============================] - 0s 5ms/step - loss: 2.2519 - accuracy: 0.1538 - val_loss: 2.3562 - val_accuracy: 0.0900
Epoch 7/30
25/25 [==============================] - 0s 5ms/step - loss: 2.2366 - accuracy: 0.1700 - val_loss: 2.3623 - val_accuracy: 0.0850
Epoch 8/30
25/25 [=

In [ ]:
test_data = np.random.random((10, 150))

model.predict(test_data)

1/1 [==============================] - 0s 51ms/step


array([[0.04190328, 0.06830245, 0.07003916, 0.19241476, 0.22956866,
        0.08644944, 0.0661509 , 0.05390946, 0.14237788, 0.04888397],
       [0.11018077, 0.08433562, 0.05531304, 0.09673166, 0.1324608 ,
        0.08855868, 0.06751665, 0.10089213, 0.17452073, 0.08948997],
       [0.05246257, 0.0678734 , 0.10145671, 0.21533747, 0.06926765,
        0.11272381, 0.1192733 , 0.04338669, 0.08621297, 0.13200541],
       [0.0297448 , 0.14515248, 0.1248142 , 0.21235442, 0.05585111,
        0.10406794, 0.05859556, 0.03107493, 0.12154969, 0.11679477],
       [0.06094715, 0.01596935, 0.07473637, 0.17162777, 0.20626488,
        0.07143413, 0.04784877, 0.07739826, 0.06861252, 0.20516074],
       [0.06970242, 0.03527624, 0.06914102, 0.13180165, 0.03633995,
        0.12766188, 0.1093304 , 0.06813633, 0.06510087, 0.28750923],
       [0.16920121, 0.13380283, 0.09203794, 0.09740812, 0.02825983,
        0.08696984, 0.09684772, 0.06912096, 0.13633694, 0.09001464],
       [0.10057423, 0.05692308, 0.0779007

In [ ]:
f = model.predict(test_data)
np.where(f[1] == max(f[1]))   # 👈👈👈👈👈👈👈 dla pierwszej próbki

1/1 [==============================] - 0s 21ms/step


(array([8]),)

# Przykład regresji

In [ ]:
data = np.random.random((1000, 150))
labels = 50 * np.random.random(1000)

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150, )))
model.add(Dense(units=1))  # jedna wartość

model.compile(optimizer='rmsprop',
              loss='mse')

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/30
25/25 [==============================] - 1s 8ms/step - loss: 588.9349 - val_loss: 331.7937
Epoch 2/30
25/25 [==============================] - 0s 3ms/step - loss: 313.2241 - val_loss: 210.7455
Epoch 3/30
25/25 [==============================] - 0s 3ms/step - loss: 228.1360 - val_loss: 204.2363
Epoch 4/30
25/25 [==============================] - 0s 3ms/step - loss: 221.8185 - val_loss: 206.8299
Epoch 5/30
25/25 [==============================] - 0s 3ms/step - loss: 221.3848 - val_loss: 206.9506
Epoch 6/30
25/25 [==============================] - 0s 3ms/step - loss: 219.9021 - val_loss: 200.4776
Epoch 7/30
25/25 [==============================] - 0s 3ms/step - loss: 220.6288 - val_loss: 202.9617
Epoch 8/30
25/25 [==============================] - 0s 4ms/step - loss: 219.5566 - val_loss: 201.5306
Epoch 9/30
25/25 [==============================] - 0s 4ms/step - loss: 218.9528 - val_loss: 201.0887
Epoch 10/30
25/25 [==============================] - 0s 3ms/step - loss: 218.0329 

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150, )))
model.add(Dense(units=1))  # jedna wartość

model.compile(optimizer='rmsprop',
              loss='mae',
              metrics=['mse'])

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/30
25/25 [==============================] - 1s 9ms/step - loss: 20.9261 - mse: 623.9875 - val_loss: 16.1240 - val_mse: 388.7077
Epoch 2/30
25/25 [==============================] - 0s 3ms/step - loss: 15.9512 - mse: 369.2285 - val_loss: 12.8985 - val_mse: 238.2591
Epoch 3/30
25/25 [==============================] - 0s 3ms/step - loss: 13.5443 - mse: 249.0342 - val_loss: 12.0451 - val_mse: 201.2206
Epoch 4/30
25/25 [==============================] - 0s 3ms/step - loss: 12.9689 - mse: 222.7068 - val_loss: 12.1690 - val_mse: 206.4014
Epoch 5/30
25/25 [==============================] - 0s 4ms/step - loss: 12.8657 - mse: 221.5311 - val_loss: 12.3367 - val_mse: 213.5543
Epoch 6/30
25/25 [==============================] - 0s 3ms/step - loss: 12.8560 - mse: 223.7590 - val_loss: 12.2804 - val_mse: 211.2800
Epoch 7/30
25/25 [==============================] - 0s 3ms/step - loss: 12.8302 - mse: 221.8669 - val_loss: 12.2976 - val_mse: 211.9522
Epoch 8/30
25/25 [==============================

In [ ]:
test_data = np.random.random((10, 150))

model.predict(test_data)

1/1 [==============================] - 0s 79ms/step


array([[27.838123],
       [24.232353],
       [26.290127],
       [26.64579 ],
       [26.871582],
       [25.927542],
       [24.661886],
       [24.799732],
       [26.35321 ],
       [26.408588]], dtype=float32)