<a href="https://colab.research.google.com/github/kjedrzejczak/Wprowadzenie_do_sieci_neuronowych-Tensorflow_2.0-Keras/blob/main/Funkcje_aktywacji_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
import math

np.set_printoptions(precision=6)

Funkcja ReLu

In [2]:
def max_relu(x):
  return max(x, 0.0)

In [3]:
for i in [-10, -5, 0, 120, 30]:
  print(max_relu(i))

0.0
0.0
0
120
30


In [4]:
import numpy as np

data = np.random.randn(50)
data = sorted(data)
data

[-2.1114924274115143,
 -1.910660918015275,
 -1.6727146767035779,
 -1.5272073778222328,
 -1.152780419898421,
 -1.1045647077905698,
 -1.076107692838103,
 -0.9627068764066145,
 -0.9001874209215945,
 -0.7414537919556093,
 -0.7404644737078071,
 -0.6413575178337676,
 -0.5218330252882891,
 -0.5216754830127578,
 -0.467271698625676,
 -0.46656758681341454,
 -0.4515745279583279,
 -0.449813856541857,
 -0.3970256246030771,
 -0.3700228348761547,
 -0.34869464845698317,
 -0.3063871394388506,
 -0.1206061170363911,
 0.00647260170224222,
 0.09288410776987735,
 0.09465972139064018,
 0.14580246734123226,
 0.14912856709656203,
 0.18127466176167975,
 0.219763240269461,
 0.2602218736607512,
 0.27961746507511187,
 0.35182340419152186,
 0.35414826300287244,
 0.49040537501192416,
 0.6440574141309335,
 0.6448221471828863,
 0.6833738902670731,
 0.7203064400322594,
 0.7224963364491311,
 0.7708698503599731,
 0.8287094508658823,
 0.8413792305093502,
 0.9244106504470024,
 1.1386691990311466,
 1.2451579108848334,
 1.40

In [5]:
max_relu_data = np.array([max_relu(x) for x in data])
max_relu_data

array([0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.006473,
       0.092884, 0.09466 , 0.145802, 0.149129, 0.181275, 0.219763,
       0.260222, 0.279617, 0.351823, 0.354148, 0.490405, 0.644057,
       0.644822, 0.683374, 0.720306, 0.722496, 0.77087 , 0.828709,
       0.841379, 0.924411, 1.138669, 1.245158, 1.400412, 1.545102,
       1.758501, 2.964912])

In [6]:
df = pd.DataFrame({'data':data, 'max_relu_data':max_relu_data})
df.head()

data  max_relu_data
0 -2.111492            0.0
1 -1.910661            0.0
2 -1.672715            0.0
3 -1.527207            0.0
4 -1.152780            0.0

In [7]:
px.line(df, x='data', y='max_relu_data', width=700, height=400, title='ReLu Function')

Funkcja Sigmoid

In [8]:
def sigmoid(x):
  return 1/(1 + np.exp(-x))

In [9]:
for i in [-10, -5, 0, 120, 30]:
  print(sigmoid(i))

4.5397868702434395e-05
0.0066928509242848554
0.5
1.0
0.9999999999999065


In [10]:
sigmoid_data = np.array([sigmoid(x) for x in data])
sigmoid_data

array([0.107985, 0.128907, 0.158063, 0.178403, 0.239982, 0.248886,
       0.254243, 0.276337, 0.289012, 0.322686, 0.322903, 0.34494 ,
       0.372424, 0.372461, 0.385262, 0.385429, 0.388986, 0.389405,
       0.402027, 0.408536, 0.413699, 0.423997, 0.469885, 0.501618,
       0.523204, 0.523647, 0.536386, 0.537213, 0.545195, 0.554721,
       0.564691, 0.569452, 0.58706 , 0.587623, 0.620202, 0.65567 ,
       0.655843, 0.664491, 0.672674, 0.673156, 0.683709, 0.696082,
       0.698756, 0.71594 , 0.757435, 0.776461, 0.802249, 0.824205,
       0.853022, 0.950964])

In [11]:
df_sigmoid = pd.DataFrame({'data':data, 'sigmoid_data':sigmoid_data})
df_sigmoid.head()

data  sigmoid_data
0 -2.111492      0.107985
1 -1.910661      0.128907
2 -1.672715      0.158063
3 -1.527207      0.178403
4 -1.152780      0.239982

In [12]:
px.line(df_sigmoid, x='data', y='sigmoid_data', width=700, height=400, title='ReLu Function')

Tangens hiperboliczy  = Tanh

In [13]:
def tanh(x):
  return (np.exp(x) - np.exp(-x))  /  (np.exp(x) + np.exp(-x))

In [14]:
data = 2 * np.random.randn(60)
data = sorted(data)
data

[-3.5222808345340266,
 -3.2610463715013034,
 -2.989055627731198,
 -2.9533308978653934,
 -2.780274532091925,
 -2.7431953120274155,
 -2.639344947847211,
 -2.2955106262247287,
 -2.27225033431709,
 -2.2378472617640175,
 -1.8287253705907047,
 -1.4437682819934299,
 -1.2733579941815891,
 -1.2319160870175048,
 -1.1160408141679734,
 -1.0370460255661513,
 -0.8777018329627085,
 -0.8334604431425553,
 -0.45064691920326677,
 -0.43928636612913835,
 -0.3268601709476394,
 -0.32136763771580923,
 -0.2913012244372635,
 -0.2660359245985866,
 -0.2496505750774427,
 -0.22185743825381343,
 0.06637401639308767,
 0.17175020018237125,
 0.2130920599597006,
 0.23126578770007442,
 0.24744088003135611,
 0.36366925395102434,
 0.4136074668164853,
 0.4614353581747198,
 0.4760315246602337,
 0.5410581346065143,
 0.7922935729834779,
 0.8002045085255965,
 0.8315222867094109,
 0.9057910036353402,
 0.9728196373241802,
 0.992618928810062,
 1.029362794248023,
 1.059309760612241,
 1.1746239474034295,
 1.2425065346420048,
 1.6363

In [15]:
tanh_data = np.array([tanh(x) for x in data])
tanh_data

array([-0.998257, -0.997063, -0.994946, -0.994572, -0.992336, -0.991749,
       -0.989854, -0.979919, -0.978972, -0.977492, -0.949701, -0.894454,
       -0.854705, -0.843134, -0.806187, -0.776719, -0.705266, -0.68233 ,
       -0.422431, -0.413053, -0.315697, -0.310743, -0.283332, -0.259932,
       -0.24459 , -0.218288,  0.066277,  0.170081,  0.209924,  0.227229,
        0.242512,  0.348442,  0.391531,  0.431253,  0.44306 ,  0.493789,
        0.659706,  0.664151,  0.681293,  0.719106,  0.749941,  0.758477,
        0.773653,  0.7854  ,  0.825749,  0.846169,  0.926957,  0.927023,
        0.932087,  0.960516,  0.963357,  0.966095,  0.967498,  0.980325,
        0.981288,  0.981718,  0.989382,  0.996321,  0.996575,  0.997706])

In [16]:
df_tanh = pd.DataFrame({'data':data, 'Thanh':tanh_data})
df_tanh.head()

data     Thanh
0 -3.522281 -0.998257
1 -3.261046 -0.997063
2 -2.989056 -0.994946
3 -2.953331 -0.994572
4 -2.780275 -0.992336

In [17]:
px.line(df_tanh, x='data', y='Thanh', width=700, height=400, title='ReLu Function')

Funkcja Softmax - dla problemów klasyfikacji wieloklasowej

In [18]:
def softmax(x):
  e_x = np.exp(x)
  denominator = np.sum(e_x, axis=1)
  denominator = denominator[:, np.newaxis]
  return e_x / denominator

In [19]:
data = np.random.randn(4, 5)
data

array([[ 1.260706, -1.465753,  0.265183, -0.391296,  0.485102],
       [-1.577023, -1.28558 , -1.525058, -1.36697 , -0.949506],
       [-1.220891, -0.761707,  0.137223,  0.586455, -1.568552],
       [-1.029628,  1.046922,  1.201676,  0.039924, -1.487001]])

In [21]:
result = softmax(data)
result

array([[0.47914 , 0.03136 , 0.177057, 0.091835, 0.220608],
       [0.153884, 0.205952, 0.162092, 0.189854, 0.288218],
       [0.075345, 0.119255, 0.293007, 0.459173, 0.053219],
       [0.045796, 0.365311, 0.426453, 0.133453, 0.028986]])

In [22]:
result.sum(axis=1)

array([1., 1., 1., 1.])